name: NotJustNameplates
version: "${version}"
main: me.youhavetrouble.notjustnameplates.NotJustNameplates
api-version: "1.21.10"
authors: ["YouHaveTrouble"]
description: Nameplates using display entities
website: https://youhavetrouble.me
dependencies:
  - name: PlaceholderAPI
    required: false
  - name: SuperVanish
    required: false
  - name: PremiumVanish
    required: false
  - name: VanishNoPacket
    required: false
load-after:
  - name: PlaceholderAPI
  - name: SuperVanish
  - name: PremiumVanish
  - name: VanishNoPacket